spring:
  batch:
    job:
      names: ${job.name:NONE} #spring.batch.job.names?? job.name????? ??? ?? -> ?? ?? ?? ??
    jdbc:
      initialize-schema: always #h2? ??  ?? db? embedded? ??
  datasource:
    driver-class-name: org.h2.Driver
    data: classpath:person.sql
